apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-docker-local
  labels:
    app: cicd-docker-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-docker-local
  template:
    metadata:
      labels:
        app: cicd-docker-local
    spec:
      containers:
        - name: web
          image: docker.io/DOCKERHUB_USERNAME/cicd-docker-local:latest  # <-- replace DOCKERHUB_USERNAME
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-docker-local
spec:
  type: NodePort
  selector:
    app: cicd-docker-local
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
